### ISSUE TITLE
Some PySimpleGUI suggestions

### ISSUE THREAD

**Issue by PySimpleGUI** [continuumsecurity/iriusrisktoolkitui#10]
Looking through your code a bit and thought I would give you a few comments.  Nothing critical, just suggestions.

Over time as PySimpleGUI has evolved, so has the coding conventions.  When a new approach is released that will be used for future programs, all of the documentation and demo programs are usually modified to match the new methods.  This is done so that newcomers aren't confused by seeing examples that have old names that are perhaps no longer in the documentation.  Great care is given to remaining backwards compatible however, so even if the older names are no longer documented, they will continue to run with no problems.

* PEP8 bindings.  All of the PySimpleGUI methods and functions now have PEP8 compliant versions.  They're recommended to be used now rather than the older ones.  The PEP8 methods are snake_case rather than CamelCase.  For example - `window.read` instead of `window.Read()`.  `window.UnHide()` is now `window.un_hide()`.  `sg.popup` instead of `sg.Popup`
* The `FindElement` method is no longer used.  Instead the "dictionary-style" lookups are used. `window[key]` is the new way or writing `window.FindElement(key)`
* The return values dictionary should be used rather than calling an element's `get` method.
* `ev is "Submit"` should be `ev == "Submit"`.  This one is actually important to fix as it's a potential bug.  `is` can be used with `None`, `True`, etc, but not strings.
* There's a new constant `WIN_CLOSED` that is returned as an event.  It makes your code more understandable to see `if event == sg.WIN_CLOSED` than `if event is None`.  It's a relatively new addition.  All of the demos and documentation has been or will be changed to reflect this.  You can safely continue to use None however, so it's not critical to change, just potentially clearer.

You've written a LOT of PySimpleGUI code!  None of these are critical for you to change (other than maybe the `is "Submit"` one... they're just suggestions.

I hope that it's been a good experience for you overall.

**Comment by v3rn3** [comment]
Thanks for your feedback!
We'll go through your comments as soon as we can. Hopefully for the next release.
Thanks also for creating such a useful Python Library for quickly creating GUIs.

**Comment by v3rn3** [comment]
Most of the suggestions were implemented. Thanks again!
