### ISSUE TITLE
Screenshots....

### ISSUE THREAD

**Issue by PySimpleGUI** [continuumsecurity/iriusrisktoolkitui#9]
Your GUI code is quite extensive which tells me that you've likely got an impressive GUI that I and I'm sure others would enjoy seeing.

Would it be possible for you to include a few screenshots in your readme?  I have a video on how to add them if you need help (I doubt you do however).

It's unusual for Python programs to have a GUI so when one does have a GUI it gets noticed.  Nothing grabs someone's attention than a screenshot of your application.  It also gives me the ability to promote or "spotlight" someone's work if I have an image.

**Comment by v3rn3** [comment]
We have some screenshots in the documentation section: https://github.com/continuumsecurity/iriusrisktoolkitui/blob/master/documentation/Readme.md
